<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'||!in_array('--development-fixtures',$argv,true)){http_response_code(404);exit(1);}
ini_set('display_errors','0');ini_set('log_errors','0');
require __DIR__.'/../services/pagamentos/PixWebhook.php';
use OneFit\Pagamentos\{PixRepositorio,PixCheckout,OrdersPixGatewayInterface,PixWebhook};
final class IntegratedFake implements OrdersPixGatewayInterface {
    public array $orders=[];public string $status='action_required';public int $creates=0;public int $reads=0;public ?Closure $duringRead=null;
    public function consultarIdentidade():array{return ['id'=>'123456','pais'=>'BR','site'=>'MLB','test_user'=>true];}
    public function criarOrder(array $p):array{$this->creates++;$key=$p['idempotencia'];$this->orders[$key]??=['id'=>'ORD'.strtoupper(str_replace('-','',$key)),'pagamento_id'=>'PAY'.strtoupper(str_replace('-','',$key)),'valor_centavos'=>$p['valor_centavos'],'external_reference'=>$p['external_reference']];return $this->response($this->orders[$key]);}
    public function consultarOrder(string $id):array{$this->reads++;if($this->duringRead){$fn=$this->duringRead;$this->duringRead=null;$fn();}foreach($this->orders as $o)if($o['id']===$id)return $this->response($o);throw new RuntimeException();}
    private function response(array $o):array{return $o+['ambiente'=>'testing','moeda'=>'BRL','recebedor_id'=>'123456','status'=>$this->status,'status_detail'=>$this->status==='processed'?'accredited':($this->status==='expired'?'expired':'waiting_transfer'),'pagamento_status'=>$this->status,'pagamento_status_detail'=>$this->status==='processed'?'accredited':($this->status==='expired'?'expired':'waiting_transfer'),'http'=>200,'request_id'=>'fake','provedor_criado_em'=>'2026-01-01T00:00:00Z','provedor_atualizado_em'=>'2026-01-01T00:01:00Z','qr_code'=>'fixture-code','qr_code_base64'=>'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aGz8AAAAASUVORK5CYII=','ticket_url'=>'https://www.mercadopago.com.br/fixture'];}
}
final class NotificationFailure extends PixRepositorio {
    public function transacao(Closure $f):mixed{throw new RuntimeException('fixture delivery failure');}
}
$n=0;$stage='setup';$ids=[];$before=[];$success=false;
function integratedCheck(bool $v):void{global $n;if(!$v)throw new RuntimeException('assertion');$n++;}
function integratedDenied(Closure $f):void{try{$f();}catch(OneFit\Pagamentos\PagamentoException){integratedCheck(true);return;}throw new RuntimeException('expected rejection');}
function integratedSnapshot(mysqli $db):array{$b=[];foreach(['usuarios','cadastro_planos','matricula','cobrancas','pagamentos','pagamento_eventos','pagamento','pedido','pedido_item','produtos','cashback','notificacoes','preferencias_usuario','enderecos_entrega','transportadoras','faixas_cep_frete','pix_reservas','pix_notificacoes','pix_testes_tecnicos'] as $t){$pk=$db->query("SHOW INDEX FROM `$t` WHERE Key_name='PRIMARY'")->fetch_assoc()['Column_name'];$rows=$db->query("SELECT * FROM `$t` ORDER BY `$pk`")->fetch_all(MYSQLI_ASSOC);$b[$t]=[count($rows),hash('sha256',serialize($rows))];}return $b;}
try{require __DIR__.'/../config/conn.php';$r=new PixRepositorio($conn);$before=integratedSnapshot($conn);$tag=bin2hex(random_bytes(8));
$r->sql("INSERT INTO usuarios (nome,senha,nacionalidade,data_nascimento,genero,cpf,endereco,cidade_estado,email,celular,status,email_verificado) VALUES ('Fixture integrado','!disabled','fixture','2000-01-01','outro',?,'fixture','fixture',?,'fixture','ativo',1)",['T'.substr($tag,0,13),$tag.'@example.invalid']);$ids['user']=$u=(int)$conn->insert_id;
$r->sql("INSERT INTO cadastro_planos (nome,valor,duracao_dias,status) VALUES (?, '50.00',31,'ativo')",['fixture-integrado-'.$tag]);$ids['plan']=$plan=(int)$conn->insert_id;
$r->sql("INSERT INTO produtos (nome,preco,estoque,cashback_valor,status) VALUES (?,'40.00',1,'2.00','ativo')",['fixture-integrado-'.$tag]);$ids['product']=$product=(int)$conn->insert_id;
$r->sql("INSERT INTO transportadoras (nome,status) VALUES (?,'ativo')",['fixture-integrado-'.$tag]);$ids['ship']=$ship=(int)$conn->insert_id;
$r->sql("INSERT INTO faixas_cep_frete (id_transportadora,cep_inicial,cep_final,valor_frete,prazo_dias) VALUES (?,'00000000','99999999','10.00',1)",[$ship]);$ids['range']=(int)$conn->insert_id;
$r->sql("INSERT INTO enderecos_entrega (id_usuario,cep,logradouro,numero,bairro,cidade,uf) VALUES (?,'00000000','fixture','0','fixture','fixture','SP')",[$u]);$ids['address']=$address=(int)$conn->insert_id;
$r->sql('INSERT INTO pix_testes_tecnicos (id_usuario,id_plano,id_produto) VALUES (?,?,?)',[$u,$plan,$product]);
$f=new IntegratedFake();$s=new PixCheckout($conn,$f);
integratedDenied(fn()=>$s->matricula(0,$plan));integratedDenied(fn()=>$s->dados($u,str_repeat('f',32)));
$stage='matricula-pending';$a=$s->matricula($u,$plan);$ref=$s->referencia($u,$a['id_cobranca']);$d=$s->dados($u,$ref);integratedCheck($d['status']==='pendente');integratedCheck($d['qr_code']!==null&&$d['qr_code_base64']!==null&&$d['ticket_url']!==null);integratedCheck($d['valor']==='50.00');$calls=$f->creates;$s->matricula($u,$plan);integratedCheck($f->creates===$calls);
$m=$r->um('SELECT * FROM matricula WHERE id_matricula=?',[$a['id_matricula']]);integratedCheck($m['data_inicio']===null&&$m['data_fim']===null);
$stage='poll-concurrency';$db2=new mysqli(onefitEnv('DB_HOST'),onefitEnv('DB_USER'),onefitEnv('DB_PASSWORD'),onefitEnv('DB_NAME'));$db2->set_charset('utf8mb4');$s2=new PixCheckout($db2,$f);
$r->sql('UPDATE pagamentos SET ultima_consulta_em=DATE_SUB(UTC_TIMESTAMP(6),INTERVAL 10 SECOND) WHERE id_cobranca=?',[$a['id_cobranca']]);
$f->duringRead=function()use($s2,$u,$ref,$f){$reads=$f->reads;$s2->dados($u,$ref,true);integratedCheck($reads===$f->reads);};$s->dados($u,$ref,true);$db2->close();
$stage='http-local';
session_id(bin2hex(random_bytes(16)));session_start();$_SESSION=['id_usuario'=>$u,'tipo_usuario'=>'aluno','csrf_token'=>bin2hex(random_bytes(32))];$sid=session_id();session_write_close();
foreach(['pages/matricula/matricula.php','pages/carrinho/carrinho.php','pages/dashboard/dashboard.php','pages/pagamentos/pix.php?r='.$ref] as $path){$ch=curl_init('http://localhost/AN25/OneFit/'.$path);curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_FOLLOWLOCATION=>true,CURLOPT_COOKIE=>'PHPSESSID='.$sid,CURLOPT_TIMEOUT=>20]);$html=curl_exec($ch);integratedCheck(curl_getinfo($ch,CURLINFO_HTTP_CODE)===200&&!preg_match('/Fatal error|Parse error|Warning:/',(string)$html));curl_close($ch);}
$ch=curl_init('http://localhost/AN25/OneFit/pages/pagamentos/api.php');curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_COOKIE=>'PHPSESSID='.$sid,CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>'acao=status&csrf_token=invalid',CURLOPT_TIMEOUT=>20]);curl_exec($ch);integratedCheck(curl_getinfo($ch,CURLINFO_HTTP_CODE)===403);curl_close($ch);session_id($sid);session_start();session_destroy();
$stage='matricula-approved';$f->status='processed';$r->sql('UPDATE pagamentos SET ultima_consulta_em=DATE_SUB(UTC_TIMESTAMP(6),INTERVAL 10 SECOND) WHERE id_cobranca=?',[$a['id_cobranca']]);$s->dados($u,$ref,true);
$m=$r->um('SELECT * FROM matricula WHERE id_matricula=?',[$a['id_matricula']]);integratedCheck($m['status']==='ativa');integratedCheck((new DateTimeImmutable($m['data_inicio']))->diff(new DateTimeImmutable($m['data_fim']))->days===31);$s->dados($u,$ref,true);integratedCheck($m===$r->um('SELECT * FROM matricula WHERE id_matricula=?',[$a['id_matricula']]));integratedCheck((int)$r->um('SELECT COUNT(*) n FROM notificacoes WHERE usuario_id=?',[$u])['n']===1);
$stage='pedido-pending';$f->status='action_required';$a=$s->pedido($u,[$product=>1],$address,$ship,'0.00');$id=$a['id_cobranca'];$ref=$s->referencia($u,$id);$c=$r->um('SELECT * FROM cobrancas WHERE id_cobranca=?',[$id]);integratedCheck($c['origem']==='marketplace');integratedCheck($r->um('SELECT status FROM pedido WHERE id_pedido=?',[$c['id_pedido']])['status']==='aguardando');integratedCheck((int)$r->um('SELECT estoque FROM produtos WHERE id_produto=?',[$product])['estoque']===1);integratedCheck((int)$r->um('SELECT COUNT(*) n FROM cashback WHERE id_usuario=?',[$u])['n']===0);
// A different cart attempt cannot consume the stock held by this pending order.
integratedDenied(fn()=>$s->pedido($u,[$product=>2],$address,$ship,'0.00'));
$calls=$f->creates;$s->pedido($u,[$product=>1],$address,$ship,'0.00');integratedCheck($f->creates===$calls);
$stage='pedido-expired';$f->status='expired';$r->sql('UPDATE pagamentos SET ultima_consulta_em=DATE_SUB(UTC_TIMESTAMP(6),INTERVAL 10 SECOND) WHERE id_cobranca=?',[$id]);$s->dados($u,$ref,true);integratedCheck($r->um('SELECT estado FROM pix_reservas WHERE id_cobranca=?',[$id])['estado']==='liberada');integratedCheck((int)$r->um('SELECT estoque FROM produtos WHERE id_produto=?',[$product])['estoque']===1);
$r->sql("UPDATE produtos SET status='inativo' WHERE id_produto=?",[$product]);integratedDenied(fn()=>$s->pedido($u,[$product=>1],$address,$ship,'0.00'));$r->sql("UPDATE produtos SET status='ativo' WHERE id_produto=?",[$product]);
$stage='pedido-approved';$f->status='action_required';$a=$s->pedido($u,[$product=>1],$address,$ship,'0.00');$id2=$a['id_cobranca'];integratedCheck($id!==$id2);$ref=$s->referencia($u,$id2);$f->status='processed';$r->sql('UPDATE pagamentos SET ultima_consulta_em=DATE_SUB(UTC_TIMESTAMP(6),INTERVAL 10 SECOND) WHERE id_cobranca=?',[$id2]);$s->dados($u,$ref,true);integratedCheck((int)$r->um('SELECT estoque FROM produtos WHERE id_produto=?',[$product])['estoque']===0);integratedCheck((int)$r->um('SELECT COUNT(*) n FROM cashback WHERE id_usuario=?',[$u])['n']===1);$s->dados($u,$ref,true);integratedCheck((int)$r->um('SELECT estoque FROM produtos WHERE id_produto=?',[$product])['estoque']===0);integratedCheck((int)$r->um('SELECT COUNT(*) n FROM notificacoes WHERE usuario_id=?',[$u])['n']===2);
$stage='webhook-duplicate';$p=$r->um('SELECT id_pagamento,order_id FROM pagamentos WHERE id_cobranca=?',[$id2]);$w=new PixWebhook($r);$key=hash('sha256','fixture'.$tag);$w->receber($key,$p['order_id'],'order');$w->receber($key,$p['order_id'],'order');integratedCheck((int)$r->um('SELECT COUNT(*) n FROM pagamento_eventos WHERE chave_evento=?',[$key])['n']===1);
// A fresh webhook must GET even after local approval, without repeating effects.
$r->sql('UPDATE pagamentos SET ultima_consulta_em=DATE_SUB(UTC_TIMESTAMP(6),INTERVAL 10 SECOND) WHERE id_cobranca=?',[$id2]);$reads=$f->reads;$w->processar($f);integratedCheck($f->reads===$reads+1);integratedCheck($r->um('SELECT processamento FROM pagamento_eventos WHERE chave_evento=?',[$key])['processamento']==='processado');
$w->processar($f);integratedCheck($f->reads===$reads+1);
$stage='unknown-webhook';$unknown=hash('sha256','unknown'.$tag);$w->receber($unknown,'ORDUNKNOWN'.$tag,'order');$w->processar($f);integratedCheck($r->um('SELECT processamento FROM pagamento_eventos WHERE chave_evento=?',[$unknown])['processamento']==='erro');$r->sql('UPDATE pagamento_eventos SET recebido_em=DATE_SUB(UTC_TIMESTAMP(6),INTERVAL 2 DAY),proxima_tentativa_em=NULL WHERE chave_evento=?',[$unknown]);$w->processar($f);integratedCheck($r->um('SELECT processamento FROM pagamento_eventos WHERE chave_evento=?',[$unknown])['processamento']==='ignorado');$r->sql('DELETE FROM pagamento_eventos WHERE chave_evento=?',[$unknown]);unset($unknown);
$stage='notification-failure';$financial=$r->um('SELECT status,encerrada_em FROM cobrancas WHERE id_cobranca=?',[$id2]);
(new OneFit\Pagamentos\PixEfeitos(new NotificationFailure($conn)))->entregar($id2);integratedCheck($financial===$r->um('SELECT status,encerrada_em FROM cobrancas WHERE id_cobranca=?',[$id2]));
$stage='manual-local';$r->sql('DELETE FROM pix_testes_tecnicos WHERE id_usuario=?',[$u]);
$r->sql("INSERT INTO cadastro_planos (nome,valor,duracao_dias,status) VALUES (?,'17.39',31,'ativo')",['fixture-manual-'.$tag]);$ids['plan_local']=$localPlan=(int)$conn->insert_id;
$_SERVER['REMOTE_ADDR']='127.0.0.1';$_SERVER['SERVER_ADDR']='127.0.0.1';$_SERVER['HTTP_HOST']='localhost';
$f->status='action_required';$a=$s->matricula($u,$localPlan);$localRef=$s->referencia($u,$a['id_cobranca']);
$m=$r->um('SELECT valor_contratado,status,data_inicio,data_fim FROM matricula WHERE id_matricula=?',[$a['id_matricula']]);integratedCheck($m['valor_contratado']==='17.39'&&$m['status']==='pendente'&&$m['data_inicio']===null&&$m['data_fim']===null);
$d=$s->dados($u,$localRef);integratedCheck($d['valor']==='50.00'&&$d['valor_plano']==='17.39'&&$d['teste_local']);
$calls=$f->creates;$s->matricula($u,$localPlan);integratedCheck($calls===$f->creates);
$_SERVER['REMOTE_ADDR']='192.0.2.1';integratedDenied(fn()=>$s->dados($u,$localRef,true));$_SERVER['REMOTE_ADDR']='127.0.0.1';
$f->status='processed';$r->sql('UPDATE pagamentos SET ultima_consulta_em=DATE_SUB(UTC_TIMESTAMP(6),INTERVAL 10 SECOND) WHERE id_cobranca=?',[$a['id_cobranca']]);$s->dados($u,$localRef,true);
$m=$r->um('SELECT status,data_inicio,data_fim,valor_contratado FROM matricula WHERE id_matricula=?',[$a['id_matricula']]);integratedCheck($m['status']==='ativa'&&$m['valor_contratado']==='17.39');$s->dados($u,$localRef,true);integratedCheck($m===$r->um('SELECT status,data_inicio,data_fim,valor_contratado FROM matricula WHERE id_matricula=?',[$a['id_matricula']]));
$success=true;
}catch(Throwable $e){echo json_encode(['failed_stage'=>$stage,'code'=>(int)$e->getCode(),'passed'=>$n]),PHP_EOL;}
finally{if($ids){try{$conn=new mysqli(onefitEnv('DB_HOST'),onefitEnv('DB_USER'),onefitEnv('DB_PASSWORD'),onefitEnv('DB_NAME'));$conn->set_charset('utf8mb4');$r=new PixRepositorio($conn);$r->transacao(function()use($r,$ids){$u=$ids['user'];
$r->sql('DELETE FROM pix_testes_tecnicos WHERE id_usuario=?',[$u]);$r->sql('DELETE FROM notificacoes WHERE usuario_id=?',[$u]);$r->sql('DELETE FROM pix_notificacoes WHERE id_usuario=?',[$u]);$r->sql('DELETE FROM cashback WHERE id_usuario=?',[$u]);$r->sql('DELETE r FROM pix_reservas r JOIN cobrancas c ON c.id_cobranca=r.id_cobranca WHERE c.id_usuario=?',[$u]);$r->sql('DELETE e FROM pagamento_eventos e JOIN pagamentos p ON p.id_pagamento=e.id_pagamento JOIN cobrancas c ON c.id_cobranca=p.id_cobranca WHERE c.id_usuario=?',[$u]);if(isset($GLOBALS['unknown']))$r->sql('DELETE FROM pagamento_eventos WHERE chave_evento=?',[$GLOBALS['unknown']]);if(isset($GLOBALS['key']))$r->sql('DELETE FROM pagamento_eventos WHERE chave_evento=?',[$GLOBALS['key']]);$r->sql('DELETE p FROM pagamentos p JOIN cobrancas c ON c.id_cobranca=p.id_cobranca WHERE c.id_usuario=?',[$u]);$r->sql('DELETE FROM cobrancas WHERE id_usuario=?',[$u]);$r->sql('DELETE pi FROM pedido_item pi JOIN pedido p ON p.id_pedido=pi.id_pedido WHERE p.id_usuario=?',[$u]);$r->sql('DELETE FROM pedido WHERE id_usuario=?',[$u]);$r->sql('DELETE FROM matricula WHERE id_usuario=?',[$u]);$r->sql('DELETE FROM enderecos_entrega WHERE id_usuario=?',[$u]);$r->sql('DELETE FROM usuarios WHERE id_usuario=?',[$u]);foreach(['range'=>['faixas_cep_frete','id_faixa'],'ship'=>['transportadoras','id_transportadora'],'product'=>['produtos','id_produto'],'plan'=>['cadastro_planos','id_plano'],'plan_local'=>['cadastro_planos','id_plano']] as $k=>[$t,$pk])if(isset($ids[$k]))$r->sql("DELETE FROM `$t` WHERE `$pk`=?",[$ids[$k]]);
});$after=integratedSnapshot($conn);integratedCheck($before===$after);echo json_encode(['passed'=>$n,'cleanup'=>'complete','old_data_unchanged'=>true]),PHP_EOL;}catch(Throwable){$success=false;echo 'Cleanup/integrity failed; review required.',PHP_EOL;}}}
exit($success?0:1);
